### ISSUE TITLE
Compatibility with Events Calendar 6.X

### ISSUE THREAD

**Issue by a-camacho** [the-events-calendar/the-events-calendar-category-colors#164] opened 2024-09-27 08:44 UTC
Hi, the plugin is not working at all for me.
Could you confirm it should be compatible with Events Calendar 6.X ?

I see that minimum version is 5.X but what about max version ?

**Comment by afragen** [comment] 2024-09-27 15:35
I can confirm that the Category Colors plugin continues to work with the current versions of The Events Calendar and The Events Calendar Pro. 

Are you having an issue?

**Comment by afragen** [comment] 2024-09-27 15:36
Calendar URL and what exactly the issue is would be helpful.

**Comment by PragueLiteraryCalendar** [comment] 2024-10-02 11:24
<img width="1273" alt="Screenshot 2024-10-02 at 13 20 20" src="https://github.com/user-attachments/assets/7643584f-50d0-4cbc-9ff8-4572595d7f6c">
@afragen I'm having the same issue, the page is as you can see from the screenshot, not appearing as it says on the website. 

When I try and set a colour, then click save, the colour is not saving on there, it goes back as if no information was in it.

**Comment by a-camacho** [comment] 2024-10-02 11:29
> <img alt="Screenshot 2024-10-02 at 13 20 20" width="1273" src="https://private-user-images.githubusercontent.com/183606180/372842643-7643584f-50d0-4cbc-9ff8-4572595d7f6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4Njg4MjUsIm5iZiI6MTcyNzg2ODUyNSwicGF0aCI6Ii8xODM2MDYxODAvMzcyODQyNjQzLTc2NDM1ODRmLTUwZDAtNGNiYy05ZmY4LTQ1NzI1OTVkN2Y2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxMTI4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWJhNDYwMmUwZTRmZTJkMTI5MjRjMDU0Y2I3ZWQ5OGZmYTczYzhhOWZhNmM3YTk2NDUwM2U0YTMxNjg5MjBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SKYUfD-gBx--X-M3dg_BQ5OCi7m4VC2Bw0ac9BFZh8U"> @afragen I'm having the same issue, the page is as you can see from the screenshot, not appearing as it says on the website.
> 
> When I try and set a colour, then click save, the colour is not saving on there, it goes back as if no information was in it. My calendar URL is https://pragueliterarycalendar.com/events/

Exactly.

**Comment by afragen** [comment] 2024-10-03 00:50
Apparently this is an issue with the core The Events Calendar plugin, likely related to a recent redesign of the admin section. We will have to wait for an update from them.

**Comment by PragueLiteraryCalendar** [comment] 2024-10-03 08:22
@afragen thank you for doing that research and letting me know. Would you be able to let me know when that's updated or is this one of those things I will just have to check on myself?

**Comment by afragen** [comment] 2024-10-03 14:50
I assume it will be fixed in the next release of The Events Calendar.

**Comment by a-camacho** [comment] 2024-10-03 20:01
Don't really understand how the problem is in Events Calendar admin, when the admin works perfectly when not using your plugin.

Anyways, I will just use a custom CSS class targetting my category to do the color.

Thanks anyway.

**Comment by afragen** [comment] 2024-10-04 03:38
Well let's unpack that. The Category Colors plugin is deeply integrated with The Events Calendar and has never had this issue until the latest release of TEC and the redesign. 

But don't worry it's being investigated.

**Comment by afragen** [comment] 2024-10-08 00:37
There is a fix being worked on for this plugin. Full functionality should return.

**Closed by afragen** 2024-10-08 00:37 UTC

**Comment by a-camacho** [comment] 2024-10-08 07:43
Thanks for the fix.

When will a new version be avalaible in Github or Wordpress Plugin Repository ?

Thank you.

**Comment by afragen** [comment] 2024-10-08 23:28
It will be in both GitHub and the plugin repo as soon as it's ready and tested.

**Comment by a-camacho** [comment] 2024-10-17 18:58
Thanks.
Any ETA ?
